export const CHANGE_ADVENTURE_NAME = "CHANGE_ADVENTURE_NAME";
export const FETCH_ENEMIES = "FETCH_ENEMIES";
export const FETCH_ENEMIES_SUCCESS = "FETCH_ENEMIES_SUCCESS";
export const FETCH_ENEMIES_ERROR = "FETCH_ENEMIES_ERROR";
export const SEARCH_ENEMY = "SEARCH_ENEMY";

